shell/fzf: inner function renaming

diff --git a/shell/fzf b/shell/fzf
--- a/shell/fzf
+++ b/shell/fzf
@@ -14,17 +14,22 @@ export FZF_DEFAULT_OPTS='
 export FZF_DEFAULT_COMMAND='ag --nocolor -l -g ""'
 
 # in tmux emit modified command.
-__fzfcmd() {
+__fzfcmd_d() {
   [ ${FZF_TMUX:-1} -eq 1 ] && echo "fzf-tmux -d${FZF_TMUX_HEIGHT:-40%}" \
     || echo "fzf"
 }
 
-# ^R to paste the selected command from history into the command line. {{{1
+__fzfcmd_l() {
+  [ ${FZF_TMUX:-1} -eq 1 ] && echo "fzf-tmux -l${FZF_TMUX_WIDTH:-30%}" \
+    || echo "fzf"
+}
+
+# ^R to paste the selected command from history into the command line.                                           {{{1
 # press ^R in the fzf UI to apply sort
 fzf-history-widget() {
   local selected restore_no_bang_hist
   if selected=( $(fc -l 1 | grep '^.\{12,\}' | sort -k2 | uniq -f1 |\
-    $(__fzfcmd) +s --tac +m -n2..,.. --tiebreak=index -q "$LBUFFER") ); then
+    $(__fzfcmd_d) +s --tac +m -n2..,.. --tiebreak=index -q "$LBUFFER") ); then
   num=$selected[1]
   if [ -n "$num" ]; then
     zle vi-fetch-history -n $num
@@ -37,13 +42,13 @@ zle     -N   fzf-history-widget
 bindkey '^R' fzf-history-widget
 # }}}1
 
-# ^Tf to insert file & paths under $(pwd) to the command line. {{{1
+# ^Tf to insert file & paths under $(pwd) to the command line.                                                   {{{1
 __fsel() {
   set -o nonomatch
   command find ./* -path '*/\.*' -prune \
     -o -type f -print \
     -o -type d -print \
-    -o -type l -print 2> /dev/null | $(__fzfcmd) -m -e | while read item; do
+    -o -type l -print 2> /dev/null | $(__fzfcmd_d) -m -e | while read item; do
   printf '%q ' "$item"
 done
 echo
@@ -71,10 +76,10 @@ zle     -N   fzf-file-widget
 bindkey '^Tf' fzf-file-widget
 # }}}1
 
-# ^Tj to insert paths from $(z -l) to the command line. {{{1
+# ^Tj to insert paths from $(z -l) to the command line.                                                          {{{1
 __zdirs() {
   set -o nonomatch
-  z -l | sed 's/[0-9.,]* *//' | $(__fzfcmd) -m -e | while read item; do
+  z -l | sed 's/[0-9.,]* *//' | $(__fzfcmd_d) -m -e | while read item; do
   printf '%q ' "$item"
 done
 echo
@@ -89,14 +94,15 @@ zle     -N   mudox-zsh-widget-zdirs
 bindkey '^Tj' mudox-zsh-widget-zdirs
 # }}}1
 
-# ^[j to cd to one of the paths in $(z -l). {{{1
+# ^[j to cd to one of the paths in $(z -l).                                                                      {{{1
 mudox-zsh-widget-j() {
   if [[ -z "$(whence z)" ]]; then
     printf "\e[31mneed z, quit...\e[0m\n"
+    return
   fi
 
   local target_dir
-  target_dir=$( z -l | sed 's/[0-9.,]* *//' | $(__fzfcmd) +m \
+  target_dir=$( z -l | sed 's/[0-9.,]* *//' | $(__fzfcmd_d) +m \
     --select-1 \
     --exit-0 \
     --extended-exact)
@@ -110,13 +116,13 @@ zle -N mudox-zsh-widget-j
 bindkey '^[j' mudox-zsh-widget-j
 #}}}1
 
-# ^[D to cd to one of directory under current path. {{{1
+# ^[D to cd to one of directory under current path.                                                              {{{1
 # do not descend into hidden directories.
 mudox-zsh-widget-c() {
   local target_dir
   target_dir=$(find ./* -path '*/\.*' -prune \
     -o -type d -print 2> /dev/null | \
-    $(__fzfcmd) +m +s --extended-exact)
+    $(__fzfcmd_d) +m +s --extended-exact)
 
   [ -n "$target_dir" ] && cd "$target_dir"
 
@@ -127,10 +133,10 @@ zle -N mudox-zsh-widget-c
 bindkey '^[D' mudox-zsh-widget-c
 #}}}1
 
-# fe [pattern] to open the selected file with the gvim in tab. {{{1
+# fe [pattern] to open the selected file with the gvim in tab.                                                   {{{1
 fe() {
   local file
-  file=$($(__fzfcmd) \
+  file=$($(__fzfcmd_d) \
     --query="$1" \
     --select-1 \
     --exit-0 \
@@ -141,9 +147,9 @@ fe() {
     Darwin )
       # for MacOS
       if whence nvim; then
-	local vim_bin='nvim'
+        local vim_bin='nvim'
       else
-	local vim_bin='mvim'
+        local vim_bin='mvim'
       fi
       ;;
     CYGWIN* )
@@ -167,18 +173,18 @@ fe() {
   fi
 } #}}}1
 
-# fkill to select & kill procces. {{{1
+# fkill to select & kill procces.                                                                                {{{1
 fkill() {
   ps | \
     sed '1d' | \
-    $(__fzfcmd) --multi --extended-exact | \
+    $(__fzfcmd_d) --multi --extended-exact | \
     awk '{print $2}' | \
     xargs kill -"${1:-9}"
 } #}}}1
 
-# cmake help selection. {{{1
+# cmake help selection.                                                                                          {{{1
 
-# cmake helps {{{2
+# cmake helps                                                                                                    {{{2
 cmh() {
   local category
   local usage="\
@@ -194,7 +200,7 @@ cmh() {
   if [[ "$#" -eq 0 ]]; then
     local categories="command\nmanual\nmodule\npolicy\nproperty\nvariable"
 
-    category=$(echo ${categories} | $(__fzfcmd) \
+    category=$(echo ${categories} | $(__fzfcmd_d) \
       --query="$2"                      \
       --select-1                        \
       --extended-exact                  \
@@ -206,35 +212,35 @@ cmh() {
   else
     case "$1" in
       c )
-	category="command"
-	;;
+        category="command"
+        ;;
       ma )
-	category="manual"
-	;;
+        category="manual"
+        ;;
       mo )
-	category="module"
-	;;
+        category="module"
+        ;;
       po )
-	category="policy"
-	;;
+        category="policy"
+        ;;
       pr )
-	category="property"
-	;;
+        category="property"
+        ;;
       v )
-	category="variable"
-	;;
+        category="variable"
+        ;;
       * )
-	printf "\e[31m%s: invalid first argument\e[0m\n" "$0"
-	echo "${usage}"
-	return
-	;;
+        printf "\e[31m%s: invalid first argument\e[0m\n" "$0"
+        echo "${usage}"
+        return
+        ;;
     esac
   fi
 
   local selection
   selection=$(cmake --help-${category}-list | \
     sed '1d' | sort | uniq |              \
-    $(__fzfcmd)                                   \
+    $(__fzfcmd_d)                                   \
     --query="$2"                          \
     --select-1                            \
     --extended-exact                      \
@@ -245,7 +251,7 @@ cmh() {
 }
 # }}}2
 
-# ctest helps {{{2
+# ctest helps                                                                                                    {{{2
 # NOTE: just a copy of cmh() above, with all 'cmake' replaced with 'ctest'.
 cth() {
   local category
@@ -262,7 +268,7 @@ cth() {
   if [[ "$#" -eq 0 ]]; then
     local categories="command\nmanual\nmodule\npolicy\nproperty\nvariable"
 
-    category=$(echo ${categories} | $(__fzfcmd) \
+    category=$(echo ${categories} | $(__fzfcmd_d) \
       --query="$2"                      \
       --select-1                        \
       --extended-exact                  \
@@ -274,35 +280,35 @@ cth() {
   else
     case "$1" in
       c )
-	category="command"
-	;;
+        category="command"
+        ;;
       ma )
-	category="manual"
-	;;
+        category="manual"
+        ;;
       mo )
-	category="module"
-	;;
+        category="module"
+        ;;
       po )
-	category="policy"
-	;;
+        category="policy"
+        ;;
       pr )
-	category="property"
-	;;
+        category="property"
+        ;;
       v )
-	category="variable"
-	;;
+        category="variable"
+        ;;
       * )
-	printf "\e[31m%s: invalid first argument\e[0m\n" "$0"
-	echo "${usage}"
-	return
-	;;
+        printf "\e[31m%s: invalid first argument\e[0m\n" "$0"
+        echo "${usage}"
+        return
+        ;;
     esac
   fi
 
   local selection
   selection=$(ctest --help-${category}-list | \
     sed '1d' | sort | uniq |              \
-    $(__fzfcmd)                                   \
+    $(__fzfcmd_d)                                   \
     --query="$2"                          \
     --select-1                            \
     --extended-exact                      \
