shell/hugo: improve hb().

diff --git a/shell/hugo b/shell/hugo
--- a/shell/hugo
+++ b/shell/hugo
@@ -1,31 +1,61 @@
+
 # hb(): build hugo site into mudox.github.io
 hb() {
+  local production='output/production'
+
+  local site_git_path="${HOME}/Git/Mudox.github.io"
+  if [ ! -e "${site_git_path}" ]; then
+    echo "\e[31mneed ${site_git_path}, quit ...\e[0m"
+    return
+  fi
+
+  if [ ! -d "${site_git_path}" ]; then
+    echo "\e[31mmissing ${site_git_path}, quit ...\e[0m"
+    return
+  fi
+
   # check if $(pwd) is a valid root of a hugo site.
   if ! [ -d "content" -a -f "config.toml" ]; then
-    echo "\e[33mcurrent path is not a valid root of hugo site\e[0m."
+    echo "\e[33mcurrent path is not a valid root of hugo site\e[0m"
     local default_site="${HOME}/Sites/hugo-site"
     if [ -d "${default_site}" ]; then
-      echo "\e[34mcd to \e[5;33m${default_site}\e[33m ...\e[0m."
+      echo "\e[34mcd to \e[7;34m${default_site} ...\e[0m"
       cd "${default_site}"
     else
-      echo "\e[31mcan not find a valid hugo site path to cd\e[0m."
+      echo "\e[31mcan not find a valid hugo site path to cd, quit ...\e[0m"
       return
     fi
   fi
 
+  echo "\e[34mstart building site ...\e[0m"
   # start hugo server
-  if [ -d "mudox.github.io" ]; then
-    hugo \
-      --source=. \
-      --destination="mudox.github.io" \
-      --buildDrafts \
-      --buildFuture \
-      --disableRSS=true \
-      --disableSitemap=true \
-      --theme="cur_theme"
-  else
-    echo "\e[31mmissing path mudox.github.io\e[0m."
+  hugo                            \
+    --source=.                    \
+    --destination="${production}" \
+    --buildDrafts                 \
+    --buildFuture                 \
+    --disableRSS=true             \
+    --disableSitemap=true         \
+    --theme="cur_theme"
+
+  if [ "$?" -ne 0 ]; then
+    echo "\e[31mbuild site failed, quit ...\e[0m"
+    return
   fi
+
+  echo "\e[34mcopying production ...\e[0m"
+  cp --recursive --target-directory="${site_git_path}" "./${production}"/* || return
+
+  # commit & push changes to github
+  cd "${site_git_path}"
+  if [ "$#" -ne 1 ]; then
+    git add . && git commit
+  else
+    git add . && git commit -m "$1"
+  fi
+
+  echo "\e[34mpushing up ...\e[0m"
+  git push
 }
 
 # hs(): hugo server for test {{{1
@@ -55,19 +85,25 @@ hs() {
 
   # check if $(pwd) is a valid root of a hugo site.
   if ! [ -d "content" -a -f "config.toml" ]; then
-    echo "\e[33mcurrent path is not a valid root of hugo site\e[0m."
+    echo "\e[33mcurrent path is not a valid root of hugo site\e[0m"
     local default_site="${HOME}/Sites/hugo-site"
     if [ -d "${default_site}" ]; then
-      echo "\e[34mcd to \e[5;33m${default_site}\e[33m ...\e[0m."
+      echo "\e[34mcd to \e[5;33m${default_site}\e[33m ...\e[0m"
       cd "${default_site}"
     else
-      echo "\e[31mcan not find a valid hugo site path to cd\e[0m."
+      echo "\e[31mcan not find a valid hugo site path to cd\e[0m"
       return
     fi
   fi
 
   # start hugo server
-  hugo server --watch --buildDrafts --buildFuture --theme="$theme" -s . &
+  hugo server                         \
+    --watch                           \
+    --buildDrafts                     \
+    --buildFuture                     \
+    --theme="$theme"                  \
+    --destination="output/production" \
+    --source=. &
 
   # open local pages in browser
   local url='http://localhost:1313'
@@ -82,17 +118,17 @@ hs() {
       firefox='/d/Program Files/Mozilla Firefox/firefox.exe'
       if [ -e "${firefox_dev}" -a -e "${firefox}" ]; then
 	select browser in "${firefox_dev}" "${firefox}"; do
-	  echo "\e[34mopen in $(basename "${browser}" '.exe')\e[0m."
+	  echo "\e[34mopen in $(basename "${browser}" '.exe')\e[0m"
 	  ${browser} "${url}" &
 	  break;
 	done
       elif [ -e "${firefox_dev}" ]; then
-	echo "\e[33monly found Firefox Deveploper Edition\e[0m."
-	echo "\e[34mopen in Firefox Developer Edition\e[0m."
+	echo "\e[33monly found Firefox Deveploper Edition\e[0m"
+	echo "\e[34mopen in Firefox Developer Edition\e[0m"
 	"${firefox_dev}" "${url}" &
       elif [ -e "${firefox}" ]; then
-	echo "\e[33monly found Firefox\e[0m."
-	echo "\e[34mopen in Firefox\e[0m."
+	echo "\e[33monly found Firefox\e[0m"
+	echo "\e[34mopen in Firefox\e[0m"
 	"${firefox}" "${url}" &
       fi
       ;;
@@ -120,7 +156,7 @@ hn() {
       /Applications/MacVim.app/Contents/MacOS/Vim -g --remote-tab "content/$1"
       ;;
     CYGWIN* )
-	 gvopen "content/$1" # the function defined shell/cygwin/cygwin
+      gvopen "content/$1" # the function defined shell/cygwin/cygwin
       ;;
     Linux )
       gvim --remote-tab "content/$1"
@@ -130,3 +166,5 @@ hn() {
       ;;
   esac
 } # }}}1
+
+# vim: filetype=zsh
