updates cmdhub scripts

diff --git a/scripts/cmdhub/osx/compile_install_neovim_from_repo b/scripts/cmdhub/osx/compile_install_neovim_from_repo
--- a/scripts/cmdhub/osx/compile_install_neovim_from_repo
+++ b/scripts/cmdhub/osx/compile_install_neovim_from_repo
@@ -1,16 +1,25 @@
 #!/usr/bin/env bash
 #x cmdhub: Compile Neovim from repo & install it to ~/.bin/neovim
 
-# backup original neovim version
 neovim_path="$HOME/.bin/neovim"
 
+# backup original neovim version
+printf "\e[32mBack up current neovim copy into ${neovim_path}.tmp\e[0m\n"
 if [[ -d $neovim_path ]]; then
   rm -rf "${neovim_path}.tmp"
   mv -T "$neovim_path" "${neovim_path}.tmp" || exit
 fi
 
+# compile neovim
 cd ~/Git/neovim || exit 1
 
 rm -rf build &>/dev/null
 make clean
-make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$HOME/.bin/neovim" install
+make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=${neovim_path}" install
+
+if (($? != 0)); then
+  printf "\e[31mCompiling failed, restore backup ...\e[0m\n"
+  mv -T ${neovim_path}.tmp ${neovim_path}
+else
+  printf "\e[34mNew neovim compiled & installed\e[0m\n"
+fi
